# Generated by Django 6.0.1 on 2026-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
    ]
